TennisWeb/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TennisData;
using TennisModel;

namespace TennisWeb.Controllers
{
	[HandleError]
	public class MatchController : Controller
	{
		public IEnumerable<Player> PlayerList { get; private set; }
		
		public MatchController()
		{
			using (var db = new TennisDb())
			{
				PlayerList = db.Players.ToArray();
			}
			//using (var dr = TennisObjects.DataAccess.GetAllPlayers())
			//	PlayerList = TennisObjects.Player.GetList(dr);
		}

		public ActionResult Index()
		{
			using (var dr = TennisObjects.DataAccess.GetAllMatches())
				return View(TennisObjects.Info.PlayerMatch.GetListAll(dr));
		}

		public ActionResult Details(int id)
		{
			using (var dr = TennisObjects.DataAccess.GetMatch(id))
				return View(TennisObjects.Match.Get(dr));
		}

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(FormCollection collection)
		{
			try
			{
				// TODO: Add insert logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		public ActionResult Edit(int id)
		{
			TennisObjects.Match match;
			using (var dr = TennisObjects.DataAccess.GetMatch(id))
				match = TennisObjects.Match.Get(dr);

			//var playerItems = PlayerList.Select(x => new SelectListItem { Value = x.ID.ToString(), Text = x.FullName }).ToList();
			ViewBag.WinnerID = new SelectList(PlayerList, "ID", "FullName", match.WinnerID.ToString());
			ViewBag.LoserID = new SelectList(PlayerList, "ID", "FullName", match.LoserID);
			//ViewData["WinnerID"] = ViewBag.WinnerID;

			return View(match);
		}

		[HttpPost]
		public ActionResult Edit(int id, FormCollection collection)
		{
			try
			{
				// TODO: Add update logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		public ActionResult Delete(int id)
		{
			return View();
		}

		[HttpPost]
		public ActionResult Delete(int id, FormCollection collection)
		{
			try
			{
				// TODO: Add delete logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}
	}
}

TennisWeb/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TennisWeb.Controllers
{
	public class PlayerController : Controller
	{

		public ActionResult Index()
		{
			using (var dr = TennisObjects.DataAccess.GetPlayerOpponentSummary(1))
				return View(TennisObjects.Info.MatchSummary.GetList(dr));
		}

		public ActionResult Details(int id)
		{
			return View(TennisObjects.Player.Get(id));
		}

		public ActionResult Edit(int id)
		{
			return View(TennisObjects.Player.Get(id));
		}

		[HttpGet]
		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(TennisObjects.Player player)
		{
			if (!ModelState.IsValid)
				return View(player);

			player.Save();
			return RedirectToAction("details", "player", new { id = player.ID });
		}
	}
}

TennisWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title - Tennis Master</title>
	<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<meta name="viewport" content="width=device-width" />
	<script src="@Url.Content("~/Scripts") type="text/javascript"></script>
	<script src="~/Scripts/knockout-2.1.0.debug.js" type="text/javascript"></script>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<header>
			<div class="content-wrapper">
				<div class="float-left">
					<p class="site-title">@Html.ActionLink("Tennis Master", "Index", "Home")</p>
				</div>
				<div class="float-right">
					<section id="login">
						@Html.Partial("_LoginPartial")
					</section>
					<nav>
						<ul id="menu">
							<li>@Html.ActionLink("Home", "Index", "Home")</li>
							<li>@Html.ActionLink("Matches", "Index", "Match")</li>
							<li>@Html.ActionLink("Players", "Index", "Player")</li>
							<li>@Html.ActionLink("Events", "Index", "Event")</li>
							<li>@Html.ActionLink("About", "About", "Home")</li>
							<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
						</ul>
					</nav>
				</div>
			</div>
	</header>
	<div id="body">
		@RenderSection("featured", required: false)
		<section class="content-wrapper main-content clear-fix">
			@RenderBody()
		</section>
	</div>
	<footer>
		<div class="content-wrapper">
			<div class="float-left">
				<p>&copy; @DateTime.Now.Year - Tennis Master</p>
			</div>
		</div>
	</footer>

	@Scripts.Render("~/bundles/jquery")
	@RenderSection("scripts", required: false)
</body>
</html>